version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    labels:
      - 'skip-release'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '@typescript-eslint/eslint-plugin'
      - dependency-name: '@typescript-eslint/parser'
      - dependency-name: '@types/node'
    labels:
      - 'skip-release'
